### ISSUE TITLE
vms_apis: create vm returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#101]
### API
POST /nodes/{nodeid}/vms 

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25182652/a10c1010-2515-11e7-8b17-ea83b0073eac.png)

### ays log
```
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/e2d85eef78c92e62d808a8c08aa6c865.py", line 32, in input
    for nic in args['nics']:
KeyError: 'nics'
[Wed19 13:30] - Job.py              :46  :j.jobcontroller.job.3b1c990a8a552cfee10725e06bbd6c4a - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/c19882409d3cfb995284f9e2316ff0e3.py", line 33, in init
    volume_container = create_nbdserver_container(service, service.parent)
  File "/tmp/actions/vm/c19882409d3cfb995284f9e2316ff0e3.py", line 76, in create_nbdserver_container
    container = container_actor.serviceCreate(instance=container_name, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 448, in serviceCreate
    return j.tools.async.wrappers.sync(self.asyncServiceCreate(instance=instance, args=args))
  File "/opt/jumpscale8/lib/JumpScale/tools/async/Wrappers.py", line 11, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 440, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 27, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 112, in _initFromActor
    args2 = await self.input(args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 615, in input
    args = await job.executeInProcess()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/e2d85eef78c92e62d808a8c08aa6c865.py", line 32, in input
    for nic in args['nics']:
KeyError: 'nics'
[Wed19 13:30] - ays_api.py          :410 :j.atyourservice                - ERROR    - Error during execution of the blueprint:
 'nics'
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/server/ays_api.py", line 407, in executeBlueprint
    await repo.blueprintExecute(path=bp.path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 474, in blueprintExecute
    await bp.load(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Blueprint.py", line 153, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 440, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 27, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)

  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 138, in _initFromActor
    await self.init()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 622, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/c19882409d3cfb995284f9e2316ff0e3.py", line 33, in init
    volume_container = create_nbdserver_container(service, service.parent)
  File "/tmp/actions/vm/c19882409d3cfb995284f9e2316ff0e3.py", line 76, in create_nbdserver_container
    container = container_actor.serviceCreate(instance=container_name, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 448, in serviceCreate
    return j.tools.async.wrappers.sync(self.asyncServiceCreate(instance=instance, args=args))
  File "/opt/jumpscale8/lib/JumpScale/tools/async/Wrappers.py", line 11, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 440, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 27, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 112, in _initFromActor
    args2 = await self.input(args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 615, in input
    args = await job.executeInProcess()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/e2d85eef78c92e62d808a8c08aa6c865.py", line 32, in input
    for nic in args['nics']:
KeyError: 'nics'
```

### SV
- Grid API : "1.1.0-alpha"
- JS : 8.2.0
- G8OS : https://bootstrap.gig.tech/kernel/g8os-1.1.0-alpha.efi

**Comment by grimpy** [comment]
This blocks cluster creation aswell
