### ISSUE TITLE
vdisks_apis: POST /vdisks returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#112]
### API
```POST /vdisks```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25228303/314f8af6-25cc-11e7-9575-09479a99384b.png)

### log
```
ERROR: Service template vdisk not found. Can't execute this blueprint ((type:input.error)
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/server/ays_api.py", line 407, in executeBlueprint
    await repo.blueprintExecute(path=bp.path)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 473, in blueprintExecute
    raise j.exceptions.Input(bp.valid_msg)
JSExceptions.Input: ERROR: Service template vdisk not found. Can't execute this blueprint ((type:input.error)
```
### SV
- Grid API : "1.1.0-alpha"
- JS : 8.2.0

**Comment by khaledkbadr** [comment]
It works swiftly for me, maybe at the time of the testing `volume` templates was not renamed to `vdisk`
