### ISSUE TITLE
vms_apis: creating vm with large specs returns 201

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#132]
### API
```POST /nodes/{nodeid}/vms```

### request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25434210/ba012b70-2a8b-11e7-8f96-d61c72c89413.png)

**get vm details**
![image](https://cloud.githubusercontent.com/assets/24386820/25434299/0e712e94-2a8c-11e7-830e-edb3ad915c49.png)

 **vm wasn't listed in client.kvm.list**
## ays log
```
Error of job: vm!vm123 (install):                                                                                    │
*TRACEBACK*********************************************************************************                          │
Traceback (most recent call last):                                                                                   │
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run                                            │
    result = self.fn(*self.args, **self.kwargs)                                                                      │
  File "/tmp/actions/vm/f7b79fe6aa04bafa5a48aea7a8476a27.py", line 236, in install                                   │
    nics=nics,                                                                                                       │
  File "/usr/local/lib/python3.5/dist-packages/g8core-0.11.1-py3.5.egg/g8core/client.py", line 1401, in create       │
    return self._client.sync('kvm.create', args)                                                                     │
  File "/usr/local/lib/python3.5/dist-packages/g8core-0.11.1-py3.5.egg/g8core/client.py", line 490, in sync          │
    raise RuntimeError('invalid response: %s' % result.state, result)                                                │
RuntimeError: ('invalid response: ERROR', STATE: ERROR                                                               │
STDOUT:                                                                                                              │
                                                                                                                     │
STDERR:                                                                                                              │
                                                                                                                     │
DATA:                                                                                                                │
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: early end of file from monitor, possi│
ble problem: Domain id=142 is tainted: high-privileges\n2017-04-26T12:21:55.146340Z qemu-system-x86_64: cannot set up│
 guest memory 'pc.ram': Cannot allocate memory')"                                                                    │
)                                                                                                                    │
                                                                                                                     │
                                                                                                                     │
******************************************************************************************                           │
                                                                                                                     │
error during execution of the run                                                                                    │
ERROR: Traceback (most recent call last):                                                                            │
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run                                            │
    result = self.fn(*self.args, **self.kwargs)                                                                      │
  File "/tmp/actions/vm/f7b79fe6aa04bafa5a48aea7a8476a27.py", line 236, in install                                   │
    nics=nics,                                                                                                       │
  File "/usr/local/lib/python3.5/dist-packages/g8core-0.11.1-py3.5.egg/g8core/client.py", line 1401, in create       │
    return self._client.sync('kvm.create', args)                                                                     │
  File "/usr/local/lib/python3.5/dist-packages/g8core-0.11.1-py3.5.egg/g8core/client.py", line 490, in sync          │
    raise RuntimeError('invalid response: %s' % result.state, result)                                                │
RuntimeError: ('invalid response: ERROR', STATE: ERROR                                                               │
STDOUT:                                                                                                              │
                                                                                                                     │
STDERR:                                                                                                              │
                                                                                                                     │
DATA:                                                                                                                │
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: early end of file from monitor, possi│
ble problem: Domain id=142 is tainted: high-privileges\n2017-04-26T12:21:55.146340Z qemu-system-x86_64: cannot set up│
 guest memory 'pc.ram': Cannot allocate memory')"                                                                    │
) ((type:runtime.error)                                    
```

**Comment by khaledkbadr** [comment]
By design Grid api lists all services, but vm creation can be checked via the `status` field

**Comment by ahmedelsayed-93** [comment]
i think the status of the vm should be ```error``` not ```halted```

### SV
grid faeae03
jumpscale 92c7a2d

**Comment by khaledkbadr** [comment]
@FastGeert Should we extend the api specs to include `error` as a vm state or should we stick to halted?

**Comment by zaibon** [comment]
I think error state would make sense.

**Comment by ahmedelsayed-93** [comment]
### SV
jumpscale 9350f89
grid 787f837
