### ISSUE TITLE
storagepools_apis: delete storagepool returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [g8os/grid#86]
API
```DELETE /nodes/{nodeid}/storagepools/{storagepoolname}```

### Api request & response
![image](https://cloud.githubusercontent.com/assets/24386820/25125021/bbc1cfaa-242d-11e7-9ef9-8e93753f53c0.png)

### ays logs
```
2017-04-18 09:51:52,299 - ...umpScale/baselib/jobcontroller/Job.py:46 - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.g8os/eaf2de7ed6a2ff410d6591f5b4ff56e3.py", line 17, in install
    storagepool = node.ensure_persistance(poolname)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/Node.py", line 87, in ensure_persistance
    disk = self._eligible_fscache_disk(disks)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/Node.py", line 54, in _eligible_fscache_disk
    return disks[0]
```

### software versions

JUMPSACLE_BRANCH = "8.2.0"
GRID_API_BRANCH = "1.1.0-alpha"
AYS_TEMPLATE_BRANCH = "1.1.0-alpha

**Comment by ahmedelsayed-93** [comment]
verification process is blocked because of #119
