### ISSUE TITLE
node.g8os service produce an error

### ISSUE THREAD

**Issue by islamTaha12** [g8os/grid#89]
blueprint:
```yaml
node.g8os__0cc47ae54510:
  redisAddr: 147.75.32.181
```

traceback:
```bash
[Tue18 15:43] - AtYourServiceRepo.py:50  :j.atyourservice                - DEBUG    - Loading AYS repo /optvar/cockpit_repos/grid
[Tue18 15:43] - Service.py          :66  :j.atyourservice.service        - INFO     - init service 0cc47ab586fe from node.g8os
[Tue18 15:43] - server.py           :410 :asyncio                        - WARNING  - Executing <Handle Task._step created at /usr/local/lib/python3.5/dist-packages/sanic/server.py:179> took 0.256 seconds
[Tue18 15:43] - Job.py              :47  :j.jobcontroller.job.ef5ebc582d285372727e67c215163a6e - INFO     - >>>>future exception None 
[Tue18 15:43] - Job.py              :72  :j.jobcontroller.job.ef5ebc582d285372727e67c215163a6e - INFO     - job job: node.g8os!0cc47ab586fe (input) done sucessfuly
[Tue18 15:43] - bcd1c39f485d2ad3a2bee0555c7a44c1.py:169 :j.jobcontroller.job.2723cda5794312bda5ffd929a76f0d1a - INFO     - create storage pool for fuse cache
[Tue18 15:43] - selector_events.py  :53  :asyncio                        - DEBUG    - Using selector: EpollSelector
[Tue18 15:43] - Service.py          :66  :j.atyourservice.service        - INFO     - init service 0cc47ab586fe_fscache from storagepool
[Tue18 15:43] - Job.py              :47  :j.jobcontroller.job.9326fcaf6dfa0d63d76586937d4e99c5 - INFO     - >>>>future exception None 
[Tue18 15:43] - Job.py              :72  :j.jobcontroller.job.9326fcaf6dfa0d63d76586937d4e99c5 - INFO     - job job: storagepool!0cc47ab586fe_fscache (input) done sucessfuly
[Tue18 15:43] - Job.py              :47  :j.jobcontroller.job.2723cda5794312bda5ffd929a76f0d1a - INFO     - >>>>future exception ERROR: could not find parent:0cc47ae5455e for service:storagepool!0cc47ab586fe_fscache, found 0 ((type:i
nput.error) 
[Tue18 15:43] - Job.py              :63  :j.jobcontroller.job.2723cda5794312bda5ffd929a76f0d1a - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.g8os/bcd1c39f485d2ad3a2bee0555c7a44c1.py", line 172, in init
    storagepool.ays.create(service.aysrepo)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/atyourservice/StoragePool.py", line 21, in create
    return actor.serviceCreate(instance=self._obj.name, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 458, in serviceCreate
    return j.tools.async.wrappers.sync(self.asyncServiceCreate(instance=instance, args=args))
  File "/opt/jumpscale8/lib/JumpScale/tools/async/Wrappers.py", line 11, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 450, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 27, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 129, in _initFromActor
    parent = await self._initParent(actor, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 183, in _initParent
    (parent_name, self), level=1, source="", tags="", msgpub="")
JSExceptions.Input: ERROR: could not find parent:0cc47ae5455e for service:storagepool!0cc47ab586fe_fscache, found 0 ((type:input.error)
[Tue18 15:43] - ays_api.py          :410 :j.atyourservice                - ERROR    - Error during execution of the blueprint:
 ERROR: could not find parent:0cc47ae5455e for service:storagepool!0cc47ab586fe_fscache, found 0 ((type:input.error)
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/server/ays_api.py", line 407, in executeBlueprint
    await repo.blueprintExecute(path=bp.path)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/AtYourServiceRepo.py", line 474, in blueprintExecute
    await bp.load(role=role, instance=instance)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Blueprint.py", line 153, in load
    await actor.asyncServiceCreate(instance=bpinstance, args=args)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 450, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 27, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 142, in _initFromActor
    await self.init()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 626, in init
    await job.executeInProcess()
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110786)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.g8os/bcd1c39f485d2ad3a2bee0555c7a44c1.py", line 172, in init
    storagepool.ays.create(service.aysrepo)
  File "/opt/jumpscale8/lib/JumpScale/sal/g8os/atyourservice/StoragePool.py", line 21, in create
    return actor.serviceCreate(instance=self._obj.name, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 458, in serviceCreate
    return j.tools.async.wrappers.sync(self.asyncServiceCreate(instance=instance, args=args))
  File "/opt/jumpscale8/lib/JumpScale/tools/async/Wrappers.py", line 11, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Actor.py", line 450, in asyncServiceCreate
    service = await Service.init_from_actor(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 34, in init_from_actor
    raise e
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 27, in init_from_actor
    await self._initFromActor(actor=actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 129, in _initFromActor
    parent = await self._initParent(actor, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/lib/Service.py", line 183, in _initParent
    (parent_name, self), level=1, source="", tags="", msgpub="")
JSExceptions.Input: ERROR: could not find parent:0cc47ae5455e for service:storagepool!0cc47ab586fe_fscache, found 0 ((type:input.error)
```

**Version**
JS 8.2.0

**Comment by khaledkbadr** [comment]
Use `0cc47ae5455e` as the name node service

**Comment by islamTaha12** [comment]
I'm using it already
